// ReduxSetup 2
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'
// ReduxSetup 15
export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING'
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS'
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED'